# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Lint Check
      run: ./gradlew lint

    - name: Save Lint Report
      uses: actions/upload-artifact@v1
      with:
        name: lint-result
        path: app/build/reports/lint-results-debug.html

    - name: Execute Unit Tests
      run: ./gradlew test

    - name: Save Unit Test Report
      uses: actions/upload-artifact@v1
      with:
        name: unit-test-result
        path: app/build/reports/tests/testDebugUnitTest/
